title: "Ma, Qi"
author: "Qi Ma"
description: "Mathematics define the world"
permalink: /:title/
lang: "en, cn"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Use kramdown for Markdown rendering
markdown: kramdown
kramdown:
  math_engine: mathjax  # Use MathJax for rendering math

# Layout
show_excerpts: true   # Show excerpts on the homepage
show_frame: true      # Add grey borders
show_sidebar: false   # Hide the sidebar
minimal: false        # Disable dark title

# Menu
navigation:
  - {file: "Seminar.md"}
  - {file: "Blog.md"}
  - {file: "Notes.md"}
  - {file: "Misc.md"}

external:
  - {title: Mail, icon: envelope, url: "qi.ma@rutgers.edu"}

comments:
  # disqus_shortname: ""    # Uncomment if you need Disqus comments
  # isso_domain: ""         # Uncomment if you need Isso comments

plugins:
  - jekyll-feed        # Enable RSS feed functionality

include:
  - _pages             # Include the _pages directory

valine:
  app_id: SFQBxRyCGBTmdz1T8FFXpEHC-gzGzoHsz       # Your LeanCloud App ID
  app_key: 2NO8H0RSbANXtdhGYhnBjU2K     # Your LeanCloud App Key
  placeholder: Welcome to comment!   # Comment box placeholder
  avatar: mm                # Commenter avatar style
  page_size: 10             # Number of comments per page
  lang: zh-CN               # Language (default is Chinese)

# Enable KaTeX (disabled, but you can set it back to true if needed)
katex: false

# MathJax Configuration
mathjax: true  # Enable MathJax
